const menuList = [
    {
        title:'首页',
        key:'/admin/home'
    },
    {
        title:'UI',
        key:'/admin/ui',
        children:[
            {
                title:'按钮',
                key:'/admin/buttons'
            },
            {
                title:'弹窗',
                key:'/admin/modals'
            },
        ]
    },
];